Repository corgibot/corgi, pull requests merged in 2018-04, with the labels that each got.

#58 JSON & Console Update
  .gitignore
  pom.xml
  src/main/java/cz/wake/corgibot/CorgiBot.java
  src/main/java/cz/wake/corgibot/commands/CommandHandler.java
  src/main/java/cz/wake/corgibot/commands/admin/SetPrefix.java
  src/main/java/cz/wake/corgibot/commands/user/Meme.java
  src/main/java/cz/wake/corgibot/listener/ChatListener.java
  src/main/java/cz/wake/corgibot/managers/BotManager.java
  src/main/java/cz/wake/corgibot/sql/ConnectionPoolManager.java
  src/main/java/cz/wake/corgibot/utils/AnsiColor.java
  src/main/java/cz/wake/corgibot/utils/CorgiLogger.java
  src/main/java/cz/wake/corgibot/utils/LoadingProperties.java
  src/main/java/cz/wake/corgibot/utils/config/Config.java
  src/main/java/cz/wake/corgibot/utils/config/ConfigLoader.java
  src/main/java/cz/wake/corgibot/utils/config/ConfigUtils.java
  src/main/resources/config-template.json
  src/main/resources/logback.xml
  src/main/resources/pre-config.yml
Labels: update

#48 Upraven příkaz %about
  src/main/java/cz/wake/corgibot/commands/user/About.java
Labels: on hold ✋

#59 Rewrite příkazů
  pom.xml
  src/main/java/cz/wake/corgibot/CorgiBot.java
  src/main/java/cz/wake/corgibot/commands/Command.java
  src/main/java/cz/wake/corgibot/commands/CommandCategory.java
  src/main/java/cz/wake/corgibot/commands/CommandHandler.java
  src/main/java/cz/wake/corgibot/commands/ICommand.java
  src/main/java/cz/wake/corgibot/commands/Rank.java
  src/main/java/cz/wake/corgibot/commands/admin/Ignore.java
  src/main/java/cz/wake/corgibot/commands/admin/LeaveGuild.java
  src/main/java/cz/wake/corgibot/commands/admin/Say.java
  src/main/java/cz/wake/corgibot/commands/admin/SetPrefix.java
  src/main/java/cz/wake/corgibot/commands/games/McStatus.java
  src/main/java/cz/wake/corgibot/commands/mod/Archive.java
  src/main/java/cz/wake/corgibot/commands/mod/Ban.java
  src/main/java/cz/wake/corgibot/commands/mod/Giveaway.java
  src/main/java/cz/wake/corgibot/commands/mod/Kick.java
  src/main/java/cz/wake/corgibot/commands/mod/Perms.java
  src/main/java/cz/wake/corgibot/commands/mod/Purge.java
  src/main/java/cz/wake/corgibot/commands/mod/RoleInfo.java
  src/main/java/cz/wake/corgibot/commands/mod/Roles.java
  src/main/java/cz/wake/corgibot/commands/mod/Warn.java
  src/main/java/cz/wake/corgibot/commands/owner/Eval.java
  src/main/java/cz/wake/corgibot/commands/owner/GuildList.java
  src/main/java/cz/wake/corgibot/commands/owner/Log.java
  src/main/java/cz/wake/corgibot/commands/owner/Stop.java
  src/main/java/cz/wake/corgibot/commands/user/About.java
  src/main/java/cz/wake/corgibot/commands/user/Avatar.java
  src/main/java/cz/wake/corgibot/commands/user/Cat.java
  src/main/java/cz/wake/corgibot/commands/user/Changelog.java
  src/main/java/cz/wake/corgibot/commands/user/Choose.java
  src/main/java/cz/wake/corgibot/commands/user/Color.java
  src/main/java/cz/wake/corgibot/commands/user/Dog.java
  src/main/java/cz/wake/corgibot/commands/user/Donate.java
  src/main/java/cz/wake/corgibot/commands/user/EightBall.java
  src/main/java/cz/wake/corgibot/commands/user/Emote.java
  src/main/java/cz/wake/corgibot/commands/user/Fact.java
  src/main/java/cz/wake/corgibot/commands/user/FullWidth.java
  src/main/java/cz/wake/corgibot/commands/user/GuildInfo.java
  src/main/java/cz/wake/corgibot/commands/user/Help.java
  src/main/java/cz/wake/corgibot/commands/user/Invite.java
  src/main/java/cz/wake/corgibot/commands/user/Meme.java
  src/main/java/cz/wake/corgibot/commands/user/Ping.java
  src/main/java/cz/wake/corgibot/commands/user/Reminder.java
  src/main/java/cz/wake/corgibot/commands/user/Stats.java
  src/main/java/cz/wake/corgibot/commands/user/Support.java
  src/main/java/cz/wake/corgibot/commands/user/Svatek.java
  src/main/java/cz/wake/corgibot/commands/user/TextToBlock.java
  src/main/java/cz/wake/corgibot/commands/user/Uptime.java
  src/main/java/cz/wake/corgibot/commands/user/UserInfo.java
  src/main/java/cz/wake/corgibot/commands/user/Weather.java
  src/main/java/cz/wake/corgibot/listener/ChatListener.java
  src/main/java/cz/wake/corgibot/utils/CorgiLogger.java
  src/main/java/cz/wake/corgibot/utils/EmoteList.java
  src/main/java/cz/wake/corgibot/utils/MessageUtils.java
  src/main/java/cz/wake/corgibot/utils/config/ConfigUtils.java
  src/main/java/cz/wake/corgibot/utils/statuses/CraftManiaService.java
Labels: core 🎛️, update
